export const initialAdminUsers = [
  {
    id: 'usr-1001',
    name: 'Ava Thompson',
    email: 'ava.thompson@wanderwise.com',
    role: 'ADMIN',
    status: 'ACTIVE',
    tripsBooked: 14,
    lastLogin: '2026-02-09',
    avatar: 'https://i.pravatar.cc/150?img=32',
  },
  {
    id: 'usr-1002',
    name: 'Liam Carter',
    email: 'liam.carter@wanderwise.com',
    role: 'USER',
    status: 'ACTIVE',
    tripsBooked: 6,
    lastLogin: '2026-02-08',
    avatar: 'https://i.pravatar.cc/150?img=14',
  },
  {
    id: 'usr-1003',
    name: 'Sophia Patel',
    email: 'sophia.patel@wanderwise.com',
    role: 'USER',
    status: 'SUSPENDED',
    tripsBooked: 2,
    lastLogin: '2026-01-28',
    avatar: 'https://i.pravatar.cc/150?img=47',
  },
  {
    id: 'usr-1004',
    name: 'Noah Kim',
    email: 'noah.kim@wanderwise.com',
    role: 'USER',
    status: 'DISABLED',
    tripsBooked: 0,
    lastLogin: 'Never',
    avatar: 'https://i.pravatar.cc/150?img=58',
  },
  {
    id: 'usr-1005',
    name: 'Mia Rodriguez',
    email: 'mia.rodriguez@wanderwise.com',
    role: 'ADMIN',
    status: 'ACTIVE',
    tripsBooked: 11,
    lastLogin: '2026-02-10',
    avatar: 'https://i.pravatar.cc/150?img=21',
  },
];

export const additionalAdminUsers = [
  {
    id: 'usr-2001',
    name: 'Ethan Walker',
    email: 'ethan.walker@wanderwise.com',
    role: 'USER',
    status: 'ACTIVE',
    tripsBooked: 3,
    lastLogin: '2026-02-06',
    avatar: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 'usr-2002',
    name: 'Olivia Nguyen',
    email: 'olivia.nguyen@wanderwise.com',
    role: 'USER',
    status: 'SUSPENDED',
    tripsBooked: 5,
    lastLogin: '2026-01-30',
    avatar: 'https://i.pravatar.cc/150?img=19',
  },
  {
    id: 'usr-2003',
    name: 'Mason Johnson',
    email: 'mason.johnson@wanderwise.com',
    role: 'USER',
    status: 'DISABLED',
    tripsBooked: 0,
    lastLogin: 'Never',
    avatar: 'https://i.pravatar.cc/150?img=61',
  },
];
